name: programmingwithkumaresan

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Install TeamViewer
        run: |
          Invoke-WebRequest -Uri "https://download.teamviewer.com/download/TeamViewer_Setup.exe" -OutFile "TeamViewer_Setup.exe"
          Start-Process -FilePath "TeamViewer_Setup.exe" -ArgumentList "/S" -Wait

      - name: Start TeamViewer
        run: |
          Start-Process "C:\Program Files\TeamViewer\TeamViewer.exe"

      - name: Time Counter
        run: python time.py
