name: programmingwithkumaresan

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Show RDP IP and Port
        run: |
          $rdpIp = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -eq "Ethernet" }).IPAddress
          $rdpPort = 3389  # Default RDP port
          Write-Host "RDP IP: $rdpIp"
          Write-Host "RDP Port: $rdpPort"

      - name: Time Counter
        run: python time.py
